export const LanguageOptions = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Arabic',
  'Akan',
  'Aragonese',
  'Abkhaz',
  'Afar',
  'Afrikaans',
  'Dutch',
  'Divehi; Dhivehi; Danish',
  'Czech',
  'Albanian',
  'Amharic',
  'Armenian',
  'Assamese',
  'Avaric',
  'Avestan',
  'Aymara',
  'Azerbaijani',
  'Bambara',
  'Bashkir',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bihari',
  'Bislama',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Burmese',
  'Valencian',
  'Chamorro',
  'Chechen',
  'Chichewa',
  'Chewa',
  'Nyanja',
  'Chinese',
  'Chuvash',
  'Cornish',
  'Corsican',
  'Cree',
  'Croatian',
  'Maldivian',
  'Esperanto',
  'Estonian',
  'Ewe',
  'Faroese',
  'Fijian',
  'Finnish',
  'Fula; Fulah; Pulaar; Pular',
  'Galician',
  'Georgian',
  'Greek, Modern',
  'Guaraní',
  'Gujarati',
  'Haitian; Haitian Creole',
  'Hausa',
  'Hebrew (modern)',
  'Herero',
  'Hindi',
  'Hiri Motu',
  'Interlingua',
  'Indonesian',
  'Interlingue',
  'Irish',
  'Igbo',
  'Inupiaq',
  'Ido',
  'Icelandic',
  'Inuktitut',
  'Japanese',
  'Javanese',
  'Kalaallisut, Greenlandic',
  'Kannada',
  'Kanuri',
  'Kashmiri',
  'Kazakh',
  'Kukiyu, Gikuyu',
  'Khmer',
  'Kinyarwanda',
  'Korean',
  'Lithuanian',
  'Macedonian',
  'Portuguese',
  'Russian',
  'Somali',
  'Swahili',
  'Swedish',
  'Turkish',
  'Ukrainian',
  'Vietnamese',
  'Yoruba',
  'Zhuang',
  'Chuang',

  // Add more languages as needed
] as const;
